# frozen_string_literal: true
#  - https://blog.toshimaru.net/ruby-immutable-string/
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
#  - https://qiita.com/kymmt90/items/0ab4027fb5c42857d759

gem "pry"
gem 'pry-doc'
gem 'pry-byebug'
